# Generated by Django 5.2.5 on 2025-08-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(blank=True, db_column='tx_name', max_length=120, null=True)),
                ('date_birth', models.DateField(db_column='dt_date_birth')),
                ('email', models.EmailField(db_column='tx_email', max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
                ('parental_rating', models.IntegerField(db_column='nb_parental_rating')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('room_type', models.IntegerField(choices=[(1, 'Normal'), (2, 'Vip'), (3, 'Three Dimensional')], db_column='cs_room_type', default=1)),
                ('room_number', models.CharField(db_column='tx_room_number', max_length=40)),
                ('seat_capacity', models.IntegerField(db_column='nr_seat_capacity')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('genre', models.ForeignKey(db_column='id_genre', on_delete=django.db.models.deletion.PROTECT, related_name='genre_movies', to='core.genre')),
                ('movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.PROTECT, related_name='movie_genres', to='core.movie')),
            ],
            options={
                'verbose_name': 'Movie Genre',
                'verbose_name_plural': 'Movie Genres',
                'db_table': 'movie_genre',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(through='core.MovieGenre', to='core.genre'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('total_value', models.FloatField(blank=True, db_column='nb_total_value', null=True)),
                ('customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.customer')),
                ('payment_method', models.ForeignKey(db_column='id_payment_method', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.paymentmethod')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='RoomMap',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('seats_layout', models.JSONField(blank=True, db_column='js_seats_layout', null=True)),
                ('room', models.ForeignKey(db_column='id_room', on_delete=django.db.models.deletion.CASCADE, related_name='room_maps', to='core.room')),
            ],
            options={
                'verbose_name': 'Room Map',
                'verbose_name_plural': 'Room Maps',
                'db_table': 'room_map',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('date_time', models.DateTimeField(db_column='dt_date_time')),
                ('movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.movie')),
                ('room', models.ForeignKey(db_column='id_room', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.room')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='SeatMap',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('seats_data', models.JSONField(db_column='js_seats_data')),
                ('session', models.ForeignKey(db_column='id_session', on_delete=django.db.models.deletion.CASCADE, related_name='seat_maps', to='core.session')),
            ],
            options={
                'verbose_name': 'Seat Map',
                'verbose_name_plural': 'Seat Maps',
                'db_table': 'seat_map',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('value', models.FloatField(db_column='nb_value')),
                ('seat_position', models.CharField(db_column='tx_seat_position', max_length=40)),
                ('purchase', models.ForeignKey(db_column='id_purchase', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.purchase')),
                ('session', models.ForeignKey(db_column='id_session', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.session')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
            },
        ),
    ]
